# Generated by Django 4.0.2 on 2022-03-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cyclist',
            fields=[
                ('user_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='cyclist_name')),
                ('team_id', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='team_name')),
                ('leader_id', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CycleResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('distance', models.FloatField()),
                ('average', models.FloatField(blank=True)),
                ('max_velocity', models.FloatField(blank=True, null=True)),
                ('route_url', models.URLField(blank=True, null=True)),
                ('cyclist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRec.cyclist')),
            ],
        ),
    ]
