# Generated by Django 4.0.2 on 2022-03-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycleresults',
            old_name='cyclist_id',
            new_name='cyclist',
        ),
    ]
